### ISSUE TITLE
SoundCloud API

### ISSUE THREAD

**Issue by DanielWGross** [DanielWGross/cardinalRecording#13]
#### Description:
Need to incorporate SoundCloud functionality into the website.  Should be done through either API access or possibly though other methods.

#### Relevant Info:
API appears to be closed for new applications but possible to use through a web widget.
[SoundCloud Developers Info](https://developers.soundcloud.com/)

#### Tasks

**Comment by mccaffertycr** [comment]
I think a better solution is to just ditch the API all together and just include the links in our Clients table then just embed with the iframe element https://soundcloud.com/pages/embed
