### ISSUE TITLE
Services Hero Image

### ISSUE THREAD

**Issue by DanielWGross** [DanielWGross/cardinalRecording#23]
#### Description
A large image that will take up the majority of the viewport when a user visits the site. At a minimum, this should be a static image but it could be a dynamic image. The client will provide an image but a placeholder should be created in the meantime.

#### Inspiration Photo:
None listed but can be provided if there is confusion on what is needed.

#### Relevant Info:
This image should be responsive to the size of the viewport.

#### Tasks

**Comment by angela-andrews** [comment]
added a hero image to services page.
